package ai.vaarta.core.complaint

import ai.vaarta.core.common.SignalCategory
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Slot-based, deterministic complaint assembly — AI_REASONING_ENGINE.md §6.1.
 * The narrative is template text, never free generation: no hallucination, fully testable.
 * Every field's provenance is recorded in [ComplaintDraft.slotsMeta] for the "verify" markers.
 */
object ComplaintBuilder {

    private val IST: ZoneId = ZoneId.of("Asia/Kolkata")
    private val isoFmt: DateTimeFormatter = DateTimeFormatter.ISO_OFFSET_DATE_TIME
    private const val DISCLAIMER =
        "Generated by VAARTA from on-device analysis of a suspicious call. " +
            "Please verify all details before filing at 1930 or cybercrime.gov.in."

    fun assemble(
        input: ComplaintInput,
        generatedAtEpochMs: Long,
        narrativeLang: String = "en",
    ): ComplaintDraft {
        val sorted = input.detectedSignals.sortedBy { it.atMs }
        val durationMin = (input.callEndEpochMs - input.callStartEpochMs).coerceAtLeast(0) / 60_000L

        val platforms = buildList {
            if (sorted.any { it.category == SignalCategory.CHANNEL_SWITCH }) {
                add("Caller attempted to move the call to WhatsApp/Skype video")
            }
        }

        val incident = Incident(
            startIso = iso(input.callStartEpochMs),
            endIso = iso(input.callEndEpochMs),
            durationMinutes = durationMin,
            callerNumbers = listOfNotNull(input.callerNumber),
            platforms = platforms,
        )

        val classification = Classification(
            scamCode = input.matchedScamCode,
            scamName = input.matchedScamName,
            confidenceBucket = bucket(input.finalScore),
            topSignals = sorted.map {
                ClassifiedSignal(it.signalId, it.category, it.stage, it.atMs, it.explain, it.quote)
            },
        )

        val complainant =
            if (input.complainantName != null || input.complainantAddress != null) {
                Complainant(input.complainantName, input.complainantAddress)
            } else null

        val loss =
            if (input.lossAmountInr != null || input.transactionRefs.isNotEmpty()) {
                Loss(input.lossAmountInr, input.transactionRefs)
            } else null

        val evidence = sorted.map { EvidenceItem(it.atMs, it.explain ?: it.category.name, it.quote) }

        val slotsMeta = buildMap {
            put("incident.startIso", SlotSource.DETECTED)
            put("incident.callerNumbers", if (input.callerNumber != null) SlotSource.DETECTED else SlotSource.DEFAULT)
            put("classification.scamName", if (input.matchedScamName != null) SlotSource.DETECTED else SlotSource.DEFAULT)
            put("classification.topSignals", SlotSource.DETECTED)
            put("complainant.name", if (input.complainantName != null) SlotSource.USER else SlotSource.DEFAULT)
            put("loss.amountInr", if (input.lossAmountInr != null) SlotSource.USER else SlotSource.DEFAULT)
            put("narrative.text", SlotSource.DETECTED)
        }

        return ComplaintDraft(
            generatedAtIso = iso(generatedAtEpochMs),
            incident = incident,
            classification = classification,
            complainant = complainant,
            loss = loss,
            narrative = Narrative(narrativeLang, renderNarrative(input, sorted, narrativeLang)),
            evidence = evidence,
            disclaimer = DISCLAIMER,
            slotsMeta = slotsMeta,
        )
    }

    private fun bucket(score: Int): String = when {
        score >= 75 -> "HIGH"
        score >= 50 -> "MEDIUM"
        else -> "LOW"
    }

    private fun iso(epochMs: Long): String = Instant.ofEpochMilli(epochMs).atZone(IST).format(isoFmt)

    private fun mmss(atMs: Long): String {
        val totalSec = atMs / 1000
        return "%02d:%02d".format(totalSec / 60, totalSec % 60)
    }

    private fun renderNarrative(input: ComplaintInput, sorted: List<DetectedSignal>, lang: String): String {
        val whenStr = iso(input.callStartEpochMs)
        return if (lang == "hi") {
            val number = input.callerNumber ?: "एक अज्ञात नंबर"
            val scam = input.matchedScamName ?: "एक संदिग्ध घोटाला"
            buildString {
                append("मुझे $whenStr (IST) पर $number से एक कॉल प्राप्त हुई।\n\n")
                append("कॉल के दौरान निम्नलिखित घोटाले के चेतावनी संकेत पाए गए:\n")
                for (s in sorted) append("  - [${mmss(s.atMs)}] ${s.explain ?: s.category.name}\n")
                append("\nयह कॉल \"$scam\" के पैटर्न से मेल खाती है।\n")
                input.lossAmountInr?.let { append("मुझसे ₹$it की ठगी हुई।\n") }
                append("\nमैं अपनी शिकायत दर्ज करने और जाँच का अनुरोध करता/करती हूँ।")
            }
        } else {
            val number = input.callerNumber ?: "an unknown number"
            val scam = input.matchedScamName ?: "a suspected scam"
            buildString {
                append("On $whenStr (IST) I received a call from $number.\n\n")
                append("During the call the following scam warning signs were detected:\n")
                for (s in sorted) append("  - [${mmss(s.atMs)}] ${s.explain ?: s.category.name}\n")
                append("\nThe call matched the pattern of $scam.\n")
                input.lossAmountInr?.let { append("I was defrauded of Rs. $it.\n") }
                append("\nI request that my complaint be registered and investigated.")
            }
        }
    }
}
